promptToReturnFromSubprocess: false
gui:
  showIcons: true
  language: 'en'
  theme:
    selectedLineBgColor:
      - reverse
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
